# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0002_auto_20170201_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='bangazon_api.Product'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
