# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangazon_api', '0002_auto_20170127_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
